### ISSUE TITLE
Extractors URL filters on /extractors differ between Obstracts and Stixify apps

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/dogesec_commons#24]
Obstracts (correct)

![image](https://github.com/user-attachments/assets/8187eaf3-1001-4e71-aafc-79e703251014)

Stixify (missing filters)

![image](https://github.com/user-attachments/assets/67f25cac-85c8-4214-8614-fd755e1d5bf6)

Why is this? (both are using same build)

**Comment by fqrious** [comment]
fixed in https://github.com/muchdogesec/dogesec_commons/pull/27
